404.html
_sass/layout/_structure.scss

404 page #11

---

_config.yml
_data/locations.yml
_includes/events/event-listing-card.html
_includes/events/presenting-optional-callout.html
_includes/locations/linkedin.html
_layouts/default.html
_layouts/events/listing.html
_sass/components/_callouts.scss
_sass/components/_toc.scss
_sass/main.scss
content/_events/2020/february.md
content/_events/2020/january.md
package-lock.json

I added in the [February meetup announcement draft](https://github.com/San-Francisco-Write-The-Docs/meetups/blob/master/planning/2020.02-sf-lightning-talks.md) from the meetups repo (updating the location details)

February 2020 Event Announcement WIP

---

Gemfile.lock
README.md
_data/locations.yml
_includes/locations/flatiron.html
_includes/locations/google-345-spear-street.html
_includes/locations/google-spear-street.html
_includes/locations/new_location.html
content/_events/2020/february.md
contributing.md

WIP Cromwell-new-venues

---

content/_announcements/march2020-covid19.md

Cromwell march announcements

---

_includes/events/event-listing-card.html
_layouts/events/event.html
content/_events/2020/march.md

Add rest of the event information for March 2020 - Camtasia Closeup

---

_data/contact.yml

*   Closes #20  
Added the YouTube Square icon and a link to our YouTube to the `contact` data file. 
This allows it to get picked up and display in the list of contact options in the site footer.

Added YouTube to our social media icon link set

---

package-lock.json
package.json

*   Closes #32  
Addressing the security alert for kind-of

Update kind-of to appropriate version for #32

---

_config.yml
content/_events/2020/june.md

Created June event. 
This is still a work in progress, because we need to verify the start time with Maggie and add her bio, if she wants to use one.

WIP: created june event and updated config.yml

---

_config.yml
content/_events/2020/july.md

created july announcement

---

_config.yml
content/_events/2020/august.md
content/_events/2020/july.md
content/_events/2020/october.md

Cromwell aug 2020

---

_config.yml
content/_events/2020/august.md
content/_events/2020/july.md
content/_events/2020/september.md

- [X ] I have served the site locally and verified that the build is successful and my changes render correctly. 
Created even announcement for September

Cromwell sept 2020

---

package-lock.json
package.json

- `N/A` I have served the site locally and verified that the build is successful and my changes render correctly. 
Closes yargs-parser dependabot issue: https://github.com/advisories/GHSA-p9pc-299p-vxgp

Updated to address yargs-parser dependabot alert

---

_config.yml
content/_announcements/march2020-covid19.md
content/_events/2020/july.md
content/_events/2020/october.md

Cromwell oct 2020

---

_config.yml
_layouts/events/event.html
content/_events/2020/august.md
content/_events/2020/december.md
content/_events/2020/july.md
content/_events/2020/june.md
content/_events/2020/may.md
content/_events/2020/november.md
content/_events/2020/october.md
content/_events/2020/september.md

Cromwell nov 2020

---

_config.yml
content/_events/2020/february21.md
content/_events/2020/november.md

- [X ] I have served the site locally and verified that the build is successful and my changes render correctly. 
|Param name |My System |
|:---|:---|
|Operating System|`macOS`|
|Ruby Version|`2.7.2`|
Created event for February 2021. Lightning Talks.

created february meetup post

---

_config.yml
content/_events/2020/march21.md

- [x ] I have served the site locally and verified that the build is successful and my changes render correctly.

created march 2021 quorum event

---

content/_announcements/jan2020-new-website.md
content/_announcements/march2021-volunteer.md

- [X ] I have served the site locally and verified that the build is successful and my changes render correctly.

Updated announcements with a call volunteers.

---

_config.yml
content/_events/2020/december.md
content/_events/2021/march21.md
content/_events/2021/may.md
content/_events/_template.md
contributing.md
may.md

- [X ] I have served the site locally and verified that the build is successful and my changes render correctly. 
Created May event posting. Updated the documentation for contributing.

Cromwell may

---

_config.yml
content/_events/2021/july.md
content/_events/2021/may.md

|Info|Yours|
|:---|:---|
|Operating System|`Mac OS`|
|Ruby Version|`ruby 2.6.6p146`|
Adding the July WTD meetup event.

Add July event

---

_layouts/events/event.html
content/_events/2021/july.md

Cromwell july2

---

_config.yml
content/_events/2021/august.md
content/_events/2021/july.md

added august event

---

_config.yml
content/_events/2021/august.md
content/_events/2021/october.md

|Info|Yours|
|:---|:---|
|Operating System|`MacOS`|
|Ruby Version|`2.6.6p146`|

Publish October event

---

_config.yml
content/_events/2021/october.md
content/_events/2022/february.md
content/_events/2022/index.md

|Info|Yours|
|:---|:---|
|Operating System|`MacOS`|
|Ruby Version|`ruby 2.6.6p146`|
Added February 2022 event

Add February 2022 event

---

_config.yml
content/_events/2022/february.md
content/_events/2022/may.md

|Info|Yours|
|:---|:---|
|Operating System|`Mac`|
|Ruby Version|`2.6.6p146`|
Adding May WTD event

Add May event
